seed = {
    alimento(meta:[key:'nome'], nome:'pao integral (uma fatia)', calorias:  49 )
    alimento(meta:[key:'nome'], nome:'iogurte milk mix (unidade)', calorias:  175 )
    alimento(meta:[key:'nome'], nome:'requeijao light (uma colher de sopa)', calorias:  40 )
    alimento(meta:[key:'nome'], nome:'banana prata (uma unidade)', calorias:  62 )
    alimento(meta:[key:'nome'], nome:'arroz branco (uma escumadeira e meia)', calorias:  109 )
    alimento(meta:[key:'nome'], nome:'feijao carioca (uma concha)', calorias:  107)
    alimento(meta:[key:'nome'], nome:'file de frango grelhado (unidade media)', calorias:  159 )
    alimento(meta:[key:'nome'], nome:'pure de batata (uma colher de sopa)', calorias: 	28)
    alimento(meta:[key:'nome'], nome:'beterraba cozida (uma unidade média)', calorias:  40 )
    alimento(meta:[key:'nome'], nome:'cenoura cozida (unidade media)', calorias:  30 )
    alimento(meta:[key:'nome'], nome:'leite desnatado (um copo 200ml)', calorias:  72 )
    alimento(meta:[key:'nome'], nome:'quadradinho chocolate talento', calorias:  35 )
    alimento(meta:[key:'nome'], nome:'iogurte corpus (unidade)', calorias:  60 )
    alimento(meta:[key:'nome'], nome:'maca (unidade)', calorias:  53 )
    alimento(meta:[key:'nome'], nome:'arroz integral (uma escumadeira e meia)', calorias:  74 )
    alimento(meta:[key:'nome'], nome:'alface (60 gramas)', calorias: 	12 )
    alimento(meta:[key:'nome'], nome:'torradas integral magic toast (unidade)', calorias:  13 )
    alimento(meta:[key:'nome'], nome:'suco de soja Nestle Sollys (copo de 200ml)', calorias:  48 )
    alimento(meta:[key:'nome'], nome:'brocolis cozido (xícara de chá)', calorias:  38 )
    alimento(meta:[key:'nome'], nome:'ovo de codorna (4 unidades)', calorias:  64 )
    alimento(meta:[key:'nome'], nome:'agua de coco (copo 200ml)', calorias:  45 )
    alimento(meta:[key:'nome'], nome:'iogurte activia (unidade)', calorias:  100 )
    alimento(meta:[key:'nome'], nome:'sopa de aveia (2 colheres de sopa)', calorias:  104 )
    alimento(meta:[key:'nome'], nome:'pao francês integral (unidade)', calorias:  127 )
    alimento(meta:[key:'nome'], nome:'cenoura crua ralada (1 colher de sopa)', calorias:  3 )
    alimento(meta:[key:'nome'], nome:'peito de peru (uma fatia)', calorias:  21 )
    alimento(meta:[key:'nome'], nome:'suco Kapo (unidade)', calorias: 	78 )
    alimento(meta:[key:'nome'], nome:'couve flor (uma xicara de cha)', calorias:  25 )
    alimento(meta:[key:'nome'], nome:'salsicha perdigao cozida (unidade)', calorias:  118 )
    alimento(meta:[key:'nome'], nome:'milho enlatado (uma colher de sopa)', calorias:  16 )
    alimento(meta:[key:'nome'], nome:'ervilha enlatada (uma colher de sopa)', calorias:  12 )
    alimento(meta:[key:'nome'], nome:'arroz integral 7 graos (uma escumadeira)', calorias:  154 )
    alimento(meta:[key:'nome'], nome:'x burguer egg com cheddar', calorias:  700 )
    alimento(meta:[key:'nome'], nome:'coca cola (290 ml)', calorias:  125 )
}